import ConsultarBajas from "@/components/maintainance"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | RESGUARDOS | BAJAS",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <div className="w-full h-full overflow-auto">
            <ConsultarBajas />
        </div>
    )
}