import ConsultarBajas from "@/components/resguardos/consultarBajas"
import { Suspense } from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | RESGUARDOS | BAJAS",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <div className="w-full h-full overflow-auto">
            <Suspense>
                <ConsultarBajas />
            </Suspense>
        </div>
    )
}