import Reportes from "@/components/reportes/inea";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | REPORTES",
    description: "Generated by create next app",
};

export default function Add() {
    return (
        <div className="max-h-full overflow-auto">
            <Reportes />
        </div>            
    )
}