// src/app/resguardos/consultar/page.tsx
import { Metadata } from "next";
import { Suspense } from "react";
import ConsultarClient from "./client";

export const metadata: Metadata = {
    title: "INVENTARIO | RESGUARDOS",
    description: "Generated by create next app",
};

// Nuevo componente de carga
const Loader = () => {
    return (
        <div className="flex flex-col items-center justify-center min-h-[60vh] w-full bg-gray-50">
            <div className="relative w-24 h-24">
                <div className="absolute top-0 left-0 w-full h-full border-8 border-gray-200 rounded-full"></div>
                <div className="absolute top-0 left-0 w-full h-full border-8 border-blue-500 rounded-full border-t-transparent animate-spin"></div>
            </div>
            <h2 className="mt-6 text-2xl font-semibold text-gray-700">Cargando</h2>
            <p className="mt-2 text-gray-500">Obteniendo información de resguardos...</p>
            <div className="mt-4 flex space-x-1">
                <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: "0ms" }}></div>
                <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: "150ms" }}></div>
                <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: "300ms" }}></div>
            </div>
        </div>
    );
};

export default function Page() {
    return (
        <Suspense fallback={<Loader />}>
            <ConsultarClient />
        </Suspense>
    );
}