import Consultar from "@/components/resguardos/consultar"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | RESGUARDOS",
    description: "Generated by create next app",
};

export default function Page({ searchParams }: { searchParams?: { [key: string]: string } }) {
    const folio = searchParams?.folio || null;
    return (
        <div className="w-full h-full overflow-auto">
            <Consultar folioParam={folio} />
        </div>
    )
}