import Levantamiento from "@/components/maintainance"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | LEVANTAMIENTO",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <div className="w-full h-full overflow-auto">
            <Levantamiento />
        </div>
    )
}