import Registro from "@/components/maintainance"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | AGREGAR BIENES",
    description: "Generated by create next app",
};

export default function Add() {
    return (
        <div className="max-h-full overflow-auto">
            <Registro />
        </div>            
    )
}