import Obsoletos from "@/components/consultas/itea/obsoletos";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | OBSOLETOS",
    description: "Generated by create next app",
};

export default function Add() {
    return (
        <div className="max-h-full overflow-auto">
            <Obsoletos />
        </div>            
    )
}