import General from "@/components/maintainance"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "INVENTARIO | CONSULTAS",
    description: "Generated by create next app",
};

export default function Add() {
    return (
        <div className="max-h-full overflow-auto">
            <General />
        </div>            
    )
}